-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR, EXTRACT(MONTH FROM SALES_DATE) MONTH, GENDER, COUNT(DISTINCT(USER_ID))
FROM USER_INFO
JOIN ONLINE_SALE USING (USER_ID)
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY 1,2,3;